//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataCap
{
    using System;
    using System.Collections.Generic;
    
    public partial class Querie
    {
        public int id { get; set; }
        public int numberWeek { get; set; }
        public int numberStudent { get; set; }
        public string topic { get; set; }
        public string observations { get; set; }
        public string idStudent { get; set; }
        public string signStudent { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
